/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.expressionlist;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>expressionlist</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class expressionlistImpl extends MinimalEObjectImpl.Container implements expressionlist
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected expressionlistImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXPRESSIONLIST;
  }

} //expressionlistImpl
