/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.functiontype;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>functiontype</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class functiontypeImpl extends MinimalEObjectImpl.Container implements functiontype
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected functiontypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.FUNCTIONTYPE;
  }

} //functiontypeImpl
