/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.index;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>index</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class indexImpl extends primaryexprauxImpl implements index
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected indexImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INDEX;
  }

} //indexImpl
