/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.elementlist;
import org.xtext.example.mydsl.myDsl.literalvalue;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>literalvalue</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.literalvalueImpl#getElementlist <em>Elementlist</em>}</li>
 * </ul>
 *
 * @generated
 */
public class literalvalueImpl extends elementImpl implements literalvalue
{
  /**
   * The cached value of the '{@link #getElementlist() <em>Elementlist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElementlist()
   * @generated
   * @ordered
   */
  protected elementlist elementlist;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected literalvalueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.LITERALVALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public elementlist getElementlist()
  {
    return elementlist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetElementlist(elementlist newElementlist, NotificationChain msgs)
  {
    elementlist oldElementlist = elementlist;
    elementlist = newElementlist;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.LITERALVALUE__ELEMENTLIST, oldElementlist, newElementlist);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setElementlist(elementlist newElementlist)
  {
    if (newElementlist != elementlist)
    {
      NotificationChain msgs = null;
      if (elementlist != null)
        msgs = ((InternalEObject)elementlist).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LITERALVALUE__ELEMENTLIST, null, msgs);
      if (newElementlist != null)
        msgs = ((InternalEObject)newElementlist).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.LITERALVALUE__ELEMENTLIST, null, msgs);
      msgs = basicSetElementlist(newElementlist, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.LITERALVALUE__ELEMENTLIST, newElementlist, newElementlist));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.LITERALVALUE__ELEMENTLIST:
        return basicSetElementlist(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.LITERALVALUE__ELEMENTLIST:
        return getElementlist();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.LITERALVALUE__ELEMENTLIST:
        setElementlist((elementlist)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LITERALVALUE__ELEMENTLIST:
        setElementlist((elementlist)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.LITERALVALUE__ELEMENTLIST:
        return elementlist != null;
    }
    return super.eIsSet(featureID);
  }

} //literalvalueImpl
