/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.poststmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>poststmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class poststmtImpl extends MinimalEObjectImpl.Container implements poststmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected poststmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.POSTSTMT;
  }

} //poststmtImpl
