/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.receivertype;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>receivertype</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class receivertypeImpl extends MinimalEObjectImpl.Container implements receivertype
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected receivertypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.RECEIVERTYPE;
  }

} //receivertypeImpl
