/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.poststmt;
import org.xtext.example.mydsl.myDsl.shortvardecl;
import org.xtext.example.mydsl.myDsl.simplestmt;
import org.xtext.example.mydsl.myDsl.typecaseclause;
import org.xtext.example.mydsl.myDsl.typeswitchguard;
import org.xtext.example.mydsl.myDsl.typeswitchstmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>simplestmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.simplestmtImpl#getTypeswitchguard <em>Typeswitchguard</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.simplestmtImpl#getTypecaseclause <em>Typecaseclause</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.simplestmtImpl#getShortvardecl <em>Shortvardecl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class simplestmtImpl extends initstmtImpl implements simplestmt
{
  /**
   * The cached value of the '{@link #getTypeswitchguard() <em>Typeswitchguard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeswitchguard()
   * @generated
   * @ordered
   */
  protected typeswitchguard typeswitchguard;

  /**
   * The cached value of the '{@link #getTypecaseclause() <em>Typecaseclause</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypecaseclause()
   * @generated
   * @ordered
   */
  protected EList<typecaseclause> typecaseclause;

  /**
   * The cached value of the '{@link #getShortvardecl() <em>Shortvardecl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShortvardecl()
   * @generated
   * @ordered
   */
  protected shortvardecl shortvardecl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected simplestmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SIMPLESTMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public typeswitchguard getTypeswitchguard()
  {
    return typeswitchguard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeswitchguard(typeswitchguard newTypeswitchguard, NotificationChain msgs)
  {
    typeswitchguard oldTypeswitchguard = typeswitchguard;
    typeswitchguard = newTypeswitchguard;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD, oldTypeswitchguard, newTypeswitchguard);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeswitchguard(typeswitchguard newTypeswitchguard)
  {
    if (newTypeswitchguard != typeswitchguard)
    {
      NotificationChain msgs = null;
      if (typeswitchguard != null)
        msgs = ((InternalEObject)typeswitchguard).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD, null, msgs);
      if (newTypeswitchguard != null)
        msgs = ((InternalEObject)newTypeswitchguard).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD, null, msgs);
      msgs = basicSetTypeswitchguard(newTypeswitchguard, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD, newTypeswitchguard, newTypeswitchguard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<typecaseclause> getTypecaseclause()
  {
    if (typecaseclause == null)
    {
      typecaseclause = new EObjectContainmentEList<typecaseclause>(typecaseclause.class, this, MyDslPackage.SIMPLESTMT__TYPECASECLAUSE);
    }
    return typecaseclause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public shortvardecl getShortvardecl()
  {
    return shortvardecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetShortvardecl(shortvardecl newShortvardecl, NotificationChain msgs)
  {
    shortvardecl oldShortvardecl = shortvardecl;
    shortvardecl = newShortvardecl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.SIMPLESTMT__SHORTVARDECL, oldShortvardecl, newShortvardecl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setShortvardecl(shortvardecl newShortvardecl)
  {
    if (newShortvardecl != shortvardecl)
    {
      NotificationChain msgs = null;
      if (shortvardecl != null)
        msgs = ((InternalEObject)shortvardecl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SIMPLESTMT__SHORTVARDECL, null, msgs);
      if (newShortvardecl != null)
        msgs = ((InternalEObject)newShortvardecl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.SIMPLESTMT__SHORTVARDECL, null, msgs);
      msgs = basicSetShortvardecl(newShortvardecl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SIMPLESTMT__SHORTVARDECL, newShortvardecl, newShortvardecl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD:
        return basicSetTypeswitchguard(null, msgs);
      case MyDslPackage.SIMPLESTMT__TYPECASECLAUSE:
        return ((InternalEList<?>)getTypecaseclause()).basicRemove(otherEnd, msgs);
      case MyDslPackage.SIMPLESTMT__SHORTVARDECL:
        return basicSetShortvardecl(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD:
        return getTypeswitchguard();
      case MyDslPackage.SIMPLESTMT__TYPECASECLAUSE:
        return getTypecaseclause();
      case MyDslPackage.SIMPLESTMT__SHORTVARDECL:
        return getShortvardecl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD:
        setTypeswitchguard((typeswitchguard)newValue);
        return;
      case MyDslPackage.SIMPLESTMT__TYPECASECLAUSE:
        getTypecaseclause().clear();
        getTypecaseclause().addAll((Collection<? extends typecaseclause>)newValue);
        return;
      case MyDslPackage.SIMPLESTMT__SHORTVARDECL:
        setShortvardecl((shortvardecl)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD:
        setTypeswitchguard((typeswitchguard)null);
        return;
      case MyDslPackage.SIMPLESTMT__TYPECASECLAUSE:
        getTypecaseclause().clear();
        return;
      case MyDslPackage.SIMPLESTMT__SHORTVARDECL:
        setShortvardecl((shortvardecl)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD:
        return typeswitchguard != null;
      case MyDslPackage.SIMPLESTMT__TYPECASECLAUSE:
        return typecaseclause != null && !typecaseclause.isEmpty();
      case MyDslPackage.SIMPLESTMT__SHORTVARDECL:
        return shortvardecl != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == poststmt.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == typeswitchstmt.class)
    {
      switch (derivedFeatureID)
      {
        case MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD: return MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD;
        case MyDslPackage.SIMPLESTMT__TYPECASECLAUSE: return MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == poststmt.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == typeswitchstmt.class)
    {
      switch (baseFeatureID)
      {
        case MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD: return MyDslPackage.SIMPLESTMT__TYPESWITCHGUARD;
        case MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE: return MyDslPackage.SIMPLESTMT__TYPECASECLAUSE;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

} //simplestmtImpl
