/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.slicetype;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>slicetype</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class slicetypeImpl extends MinimalEObjectImpl.Container implements slicetype
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected slicetypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SLICETYPE;
  }

} //slicetypeImpl
