/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.typecaseclause;
import org.xtext.example.mydsl.myDsl.typeswitchguard;
import org.xtext.example.mydsl.myDsl.typeswitchstmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>typeswitchstmt</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.typeswitchstmtImpl#getTypeswitchguard <em>Typeswitchguard</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.typeswitchstmtImpl#getTypecaseclause <em>Typecaseclause</em>}</li>
 * </ul>
 *
 * @generated
 */
public class typeswitchstmtImpl extends MinimalEObjectImpl.Container implements typeswitchstmt
{
  /**
   * The cached value of the '{@link #getTypeswitchguard() <em>Typeswitchguard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeswitchguard()
   * @generated
   * @ordered
   */
  protected typeswitchguard typeswitchguard;

  /**
   * The cached value of the '{@link #getTypecaseclause() <em>Typecaseclause</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypecaseclause()
   * @generated
   * @ordered
   */
  protected EList<typecaseclause> typecaseclause;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected typeswitchstmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TYPESWITCHSTMT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public typeswitchguard getTypeswitchguard()
  {
    return typeswitchguard;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeswitchguard(typeswitchguard newTypeswitchguard, NotificationChain msgs)
  {
    typeswitchguard oldTypeswitchguard = typeswitchguard;
    typeswitchguard = newTypeswitchguard;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD, oldTypeswitchguard, newTypeswitchguard);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeswitchguard(typeswitchguard newTypeswitchguard)
  {
    if (newTypeswitchguard != typeswitchguard)
    {
      NotificationChain msgs = null;
      if (typeswitchguard != null)
        msgs = ((InternalEObject)typeswitchguard).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD, null, msgs);
      if (newTypeswitchguard != null)
        msgs = ((InternalEObject)newTypeswitchguard).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD, null, msgs);
      msgs = basicSetTypeswitchguard(newTypeswitchguard, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD, newTypeswitchguard, newTypeswitchguard));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<typecaseclause> getTypecaseclause()
  {
    if (typecaseclause == null)
    {
      typecaseclause = new EObjectContainmentEList<typecaseclause>(typecaseclause.class, this, MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE);
    }
    return typecaseclause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD:
        return basicSetTypeswitchguard(null, msgs);
      case MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE:
        return ((InternalEList<?>)getTypecaseclause()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD:
        return getTypeswitchguard();
      case MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE:
        return getTypecaseclause();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD:
        setTypeswitchguard((typeswitchguard)newValue);
        return;
      case MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE:
        getTypecaseclause().clear();
        getTypecaseclause().addAll((Collection<? extends typecaseclause>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD:
        setTypeswitchguard((typeswitchguard)null);
        return;
      case MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE:
        getTypecaseclause().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TYPESWITCHSTMT__TYPESWITCHGUARD:
        return typeswitchguard != null;
      case MyDslPackage.TYPESWITCHSTMT__TYPECASECLAUSE:
        return typecaseclause != null && !typecaseclause.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //typeswitchstmtImpl
