/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>assignmentaux</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.assignmentaux#getPostexpressionlist <em>Postexpressionlist</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.assignmentaux#getASSIGN_OP <em>ASSIGN OP</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.assignmentaux#getExpressionlist <em>Expressionlist</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getassignmentaux()
 * @model
 * @generated
 */
public interface assignmentaux extends EObject
{
  /**
   * Returns the value of the '<em><b>Postexpressionlist</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.postexpressionlist}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Postexpressionlist</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Postexpressionlist</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getassignmentaux_Postexpressionlist()
   * @model containment="true"
   * @generated
   */
  EList<postexpressionlist> getPostexpressionlist();

  /**
   * Returns the value of the '<em><b>ASSIGN OP</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>ASSIGN OP</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>ASSIGN OP</em>' attribute.
   * @see #setASSIGN_OP(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getassignmentaux_ASSIGN_OP()
   * @model
   * @generated
   */
  String getASSIGN_OP();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.assignmentaux#getASSIGN_OP <em>ASSIGN OP</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>ASSIGN OP</em>' attribute.
   * @see #getASSIGN_OP()
   * @generated
   */
  void setASSIGN_OP(String value);

  /**
   * Returns the value of the '<em><b>Expressionlist</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.expressionlist}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressionlist</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressionlist</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getassignmentaux_Expressionlist()
   * @model containment="true"
   * @generated
   */
  EList<expressionlist> getExpressionlist();

} // assignmentaux
