/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>elementtype</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getelementtype()
 * @model
 * @generated
 */
public interface elementtype extends slicetype, slicetypeaux, channeltype
{
} // elementtype
