/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>exprcaseclause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.exprcaseclause#getExprswitchcase <em>Exprswitchcase</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.exprcaseclause#getStatementlist <em>Statementlist</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getexprcaseclause()
 * @model
 * @generated
 */
public interface exprcaseclause extends EObject
{
  /**
   * Returns the value of the '<em><b>Exprswitchcase</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exprswitchcase</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprswitchcase</em>' containment reference.
   * @see #setExprswitchcase(exprswitchcase)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getexprcaseclause_Exprswitchcase()
   * @model containment="true"
   * @generated
   */
  exprswitchcase getExprswitchcase();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.exprcaseclause#getExprswitchcase <em>Exprswitchcase</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exprswitchcase</em>' containment reference.
   * @see #getExprswitchcase()
   * @generated
   */
  void setExprswitchcase(exprswitchcase value);

  /**
   * Returns the value of the '<em><b>Statementlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statementlist</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statementlist</em>' containment reference.
   * @see #setStatementlist(statementlist)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getexprcaseclause_Statementlist()
   * @model containment="true"
   * @generated
   */
  statementlist getStatementlist();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.exprcaseclause#getStatementlist <em>Statementlist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statementlist</em>' containment reference.
   * @see #getStatementlist()
   * @generated
   */
  void setStatementlist(statementlist value);

} // exprcaseclause
