/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ifstmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ifstmt#getSimplestmt <em>Simplestmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ifstmt#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ifstmt#getBlock <em>Block</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ifstmt#getIfstmt <em>Ifstmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getifstmt()
 * @model
 * @generated
 */
public interface ifstmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Simplestmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simplestmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simplestmt</em>' containment reference.
   * @see #setSimplestmt(simplestmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getifstmt_Simplestmt()
   * @model containment="true"
   * @generated
   */
  simplestmt getSimplestmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ifstmt#getSimplestmt <em>Simplestmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simplestmt</em>' containment reference.
   * @see #getSimplestmt()
   * @generated
   */
  void setSimplestmt(simplestmt value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getifstmt_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ifstmt#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.block}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getifstmt_Block()
   * @model containment="true"
   * @generated
   */
  EList<block> getBlock();

  /**
   * Returns the value of the '<em><b>Ifstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ifstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifstmt</em>' containment reference.
   * @see #setIfstmt(ifstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getifstmt_Ifstmt()
   * @model containment="true"
   * @generated
   */
  ifstmt getIfstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ifstmt#getIfstmt <em>Ifstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ifstmt</em>' containment reference.
   * @see #getIfstmt()
   * @generated
   */
  void setIfstmt(ifstmt value);

} // ifstmt
