/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>keyedelement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.keyedelement#getKeyedelement <em>Keyedelement</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.keyedelement#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getkeyedelement()
 * @model
 * @generated
 */
public interface keyedelement extends elementlist
{
  /**
   * Returns the value of the '<em><b>Keyedelement</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.keyedelement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keyedelement</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyedelement</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getkeyedelement_Keyedelement()
   * @model containment="true"
   * @generated
   */
  EList<keyedelement> getKeyedelement();

  /**
   * Returns the value of the '<em><b>Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' containment reference.
   * @see #setElement(element)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getkeyedelement_Element()
   * @model containment="true"
   * @generated
   */
  element getElement();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.keyedelement#getElement <em>Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' containment reference.
   * @see #getElement()
   * @generated
   */
  void setElement(element value);

} // keyedelement
