/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>literalvalue</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.literalvalue#getElementlist <em>Elementlist</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getliteralvalue()
 * @model
 * @generated
 */
public interface literalvalue extends compositelit, key, element
{
  /**
   * Returns the value of the '<em><b>Elementlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Elementlist</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elementlist</em>' containment reference.
   * @see #setElementlist(elementlist)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getliteralvalue_Elementlist()
   * @model containment="true"
   * @generated
   */
  elementlist getElementlist();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.literalvalue#getElementlist <em>Elementlist</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Elementlist</em>' containment reference.
   * @see #getElementlist()
   * @generated
   */
  void setElementlist(elementlist value);

} // literalvalue
