/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>primaryexpr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.primaryexpr#getPrimaryexpraux <em>Primaryexpraux</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getprimaryexpr()
 * @model
 * @generated
 */
public interface primaryexpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Primaryexpraux</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primaryexpraux</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primaryexpraux</em>' containment reference.
   * @see #setPrimaryexpraux(primaryexpraux)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getprimaryexpr_Primaryexpraux()
   * @model containment="true"
   * @generated
   */
  primaryexpraux getPrimaryexpraux();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.primaryexpr#getPrimaryexpraux <em>Primaryexpraux</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primaryexpraux</em>' containment reference.
   * @see #getPrimaryexpraux()
   * @generated
   */
  void setPrimaryexpraux(primaryexpraux value);

} // primaryexpr
