/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>simplestmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getEmptystmt <em>Emptystmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getExpressionstmt <em>Expressionstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getSendstmt <em>Sendstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getIncdecstmt <em>Incdecstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getAssignment <em>Assignment</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getShortvardecl <em>Shortvardecl</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt()
 * @model
 * @generated
 */
public interface simplestmt extends initstmt, poststmt, typeswitchstmt
{
  /**
   * Returns the value of the '<em><b>Emptystmt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Emptystmt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emptystmt</em>' attribute.
   * @see #setEmptystmt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Emptystmt()
   * @model
   * @generated
   */
  String getEmptystmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getEmptystmt <em>Emptystmt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Emptystmt</em>' attribute.
   * @see #getEmptystmt()
   * @generated
   */
  void setEmptystmt(String value);

  /**
   * Returns the value of the '<em><b>Expressionstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressionstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressionstmt</em>' containment reference.
   * @see #setExpressionstmt(expressionstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Expressionstmt()
   * @model containment="true"
   * @generated
   */
  expressionstmt getExpressionstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getExpressionstmt <em>Expressionstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressionstmt</em>' containment reference.
   * @see #getExpressionstmt()
   * @generated
   */
  void setExpressionstmt(expressionstmt value);

  /**
   * Returns the value of the '<em><b>Sendstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sendstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sendstmt</em>' containment reference.
   * @see #setSendstmt(sendstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Sendstmt()
   * @model containment="true"
   * @generated
   */
  sendstmt getSendstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getSendstmt <em>Sendstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sendstmt</em>' containment reference.
   * @see #getSendstmt()
   * @generated
   */
  void setSendstmt(sendstmt value);

  /**
   * Returns the value of the '<em><b>Incdecstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Incdecstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Incdecstmt</em>' containment reference.
   * @see #setIncdecstmt(incdecstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Incdecstmt()
   * @model containment="true"
   * @generated
   */
  incdecstmt getIncdecstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getIncdecstmt <em>Incdecstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Incdecstmt</em>' containment reference.
   * @see #getIncdecstmt()
   * @generated
   */
  void setIncdecstmt(incdecstmt value);

  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference.
   * @see #setAssignment(assignment)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Assignment()
   * @model containment="true"
   * @generated
   */
  assignment getAssignment();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getAssignment <em>Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment</em>' containment reference.
   * @see #getAssignment()
   * @generated
   */
  void setAssignment(assignment value);

  /**
   * Returns the value of the '<em><b>Shortvardecl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Shortvardecl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shortvardecl</em>' containment reference.
   * @see #setShortvardecl(shortvardecl)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Shortvardecl()
   * @model containment="true"
   * @generated
   */
  shortvardecl getShortvardecl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getShortvardecl <em>Shortvardecl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shortvardecl</em>' containment reference.
   * @see #getShortvardecl()
   * @generated
   */
  void setShortvardecl(shortvardecl value);

} // simplestmt
