/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>simplestmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getSendstmt <em>Sendstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getIncdecstmt <em>Incdecstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getAssignment <em>Assignment</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.simplestmt#getShortvardecl <em>Shortvardecl</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt()
 * @model
 * @generated
 */
public interface simplestmt extends typeswitchstmt
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

  /**
   * Returns the value of the '<em><b>Sendstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sendstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sendstmt</em>' containment reference.
   * @see #setSendstmt(sendstmtaux)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Sendstmt()
   * @model containment="true"
   * @generated
   */
  sendstmtaux getSendstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getSendstmt <em>Sendstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sendstmt</em>' containment reference.
   * @see #getSendstmt()
   * @generated
   */
  void setSendstmt(sendstmtaux value);

  /**
   * Returns the value of the '<em><b>Incdecstmt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Incdecstmt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Incdecstmt</em>' attribute.
   * @see #setIncdecstmt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Incdecstmt()
   * @model
   * @generated
   */
  String getIncdecstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getIncdecstmt <em>Incdecstmt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Incdecstmt</em>' attribute.
   * @see #getIncdecstmt()
   * @generated
   */
  void setIncdecstmt(String value);

  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference.
   * @see #setAssignment(assignmentaux)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Assignment()
   * @model containment="true"
   * @generated
   */
  assignmentaux getAssignment();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getAssignment <em>Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment</em>' containment reference.
   * @see #getAssignment()
   * @generated
   */
  void setAssignment(assignmentaux value);

  /**
   * Returns the value of the '<em><b>Shortvardecl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Shortvardecl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shortvardecl</em>' containment reference.
   * @see #setShortvardecl(shortvardecl)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getsimplestmt_Shortvardecl()
   * @model containment="true"
   * @generated
   */
  shortvardecl getShortvardecl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.simplestmt#getShortvardecl <em>Shortvardecl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shortvardecl</em>' containment reference.
   * @see #getShortvardecl()
   * @generated
   */
  void setShortvardecl(shortvardecl value);

} // simplestmt
