/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getDeclaration <em>Declaration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getLabeledstmt <em>Labeledstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getSimplestmt <em>Simplestmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getGotstmt <em>Gotstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getReturnstmt <em>Returnstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getBreakstmt <em>Breakstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getContinuestmt <em>Continuestmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getGotostmt <em>Gotostmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getFallthroughstmt <em>Fallthroughstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getBlock <em>Block</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getIfstmt <em>Ifstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getSwitchstmt <em>Switchstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getSelectstmt <em>Selectstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getForstmt <em>Forstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.statement#getDeferstmt <em>Deferstmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement()
 * @model
 * @generated
 */
public interface statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(declaration)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Declaration()
   * @model containment="true"
   * @generated
   */
  declaration getDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(declaration value);

  /**
   * Returns the value of the '<em><b>Labeledstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Labeledstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Labeledstmt</em>' containment reference.
   * @see #setLabeledstmt(labeledstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Labeledstmt()
   * @model containment="true"
   * @generated
   */
  labeledstmt getLabeledstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getLabeledstmt <em>Labeledstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Labeledstmt</em>' containment reference.
   * @see #getLabeledstmt()
   * @generated
   */
  void setLabeledstmt(labeledstmt value);

  /**
   * Returns the value of the '<em><b>Simplestmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simplestmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simplestmt</em>' containment reference.
   * @see #setSimplestmt(simplestmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Simplestmt()
   * @model containment="true"
   * @generated
   */
  simplestmt getSimplestmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getSimplestmt <em>Simplestmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simplestmt</em>' containment reference.
   * @see #getSimplestmt()
   * @generated
   */
  void setSimplestmt(simplestmt value);

  /**
   * Returns the value of the '<em><b>Gotstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gotstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gotstmt</em>' containment reference.
   * @see #setGotstmt(gotstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Gotstmt()
   * @model containment="true"
   * @generated
   */
  gotstmt getGotstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getGotstmt <em>Gotstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gotstmt</em>' containment reference.
   * @see #getGotstmt()
   * @generated
   */
  void setGotstmt(gotstmt value);

  /**
   * Returns the value of the '<em><b>Returnstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Returnstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Returnstmt</em>' containment reference.
   * @see #setReturnstmt(returnstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Returnstmt()
   * @model containment="true"
   * @generated
   */
  returnstmt getReturnstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getReturnstmt <em>Returnstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Returnstmt</em>' containment reference.
   * @see #getReturnstmt()
   * @generated
   */
  void setReturnstmt(returnstmt value);

  /**
   * Returns the value of the '<em><b>Breakstmt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Breakstmt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Breakstmt</em>' attribute.
   * @see #setBreakstmt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Breakstmt()
   * @model
   * @generated
   */
  String getBreakstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getBreakstmt <em>Breakstmt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Breakstmt</em>' attribute.
   * @see #getBreakstmt()
   * @generated
   */
  void setBreakstmt(String value);

  /**
   * Returns the value of the '<em><b>Continuestmt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Continuestmt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Continuestmt</em>' attribute.
   * @see #setContinuestmt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Continuestmt()
   * @model
   * @generated
   */
  String getContinuestmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getContinuestmt <em>Continuestmt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Continuestmt</em>' attribute.
   * @see #getContinuestmt()
   * @generated
   */
  void setContinuestmt(String value);

  /**
   * Returns the value of the '<em><b>Gotostmt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gotostmt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gotostmt</em>' attribute.
   * @see #setGotostmt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Gotostmt()
   * @model
   * @generated
   */
  String getGotostmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getGotostmt <em>Gotostmt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gotostmt</em>' attribute.
   * @see #getGotostmt()
   * @generated
   */
  void setGotostmt(String value);

  /**
   * Returns the value of the '<em><b>Fallthroughstmt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fallthroughstmt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fallthroughstmt</em>' attribute.
   * @see #setFallthroughstmt(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Fallthroughstmt()
   * @model
   * @generated
   */
  String getFallthroughstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getFallthroughstmt <em>Fallthroughstmt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fallthroughstmt</em>' attribute.
   * @see #getFallthroughstmt()
   * @generated
   */
  void setFallthroughstmt(String value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(block)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Block()
   * @model containment="true"
   * @generated
   */
  block getBlock();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(block value);

  /**
   * Returns the value of the '<em><b>Ifstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ifstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifstmt</em>' containment reference.
   * @see #setIfstmt(ifstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Ifstmt()
   * @model containment="true"
   * @generated
   */
  ifstmt getIfstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getIfstmt <em>Ifstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ifstmt</em>' containment reference.
   * @see #getIfstmt()
   * @generated
   */
  void setIfstmt(ifstmt value);

  /**
   * Returns the value of the '<em><b>Switchstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Switchstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Switchstmt</em>' containment reference.
   * @see #setSwitchstmt(switchstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Switchstmt()
   * @model containment="true"
   * @generated
   */
  switchstmt getSwitchstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getSwitchstmt <em>Switchstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Switchstmt</em>' containment reference.
   * @see #getSwitchstmt()
   * @generated
   */
  void setSwitchstmt(switchstmt value);

  /**
   * Returns the value of the '<em><b>Selectstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Selectstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selectstmt</em>' containment reference.
   * @see #setSelectstmt(selectstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Selectstmt()
   * @model containment="true"
   * @generated
   */
  selectstmt getSelectstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getSelectstmt <em>Selectstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selectstmt</em>' containment reference.
   * @see #getSelectstmt()
   * @generated
   */
  void setSelectstmt(selectstmt value);

  /**
   * Returns the value of the '<em><b>Forstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Forstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forstmt</em>' containment reference.
   * @see #setForstmt(forstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Forstmt()
   * @model containment="true"
   * @generated
   */
  forstmt getForstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getForstmt <em>Forstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Forstmt</em>' containment reference.
   * @see #getForstmt()
   * @generated
   */
  void setForstmt(forstmt value);

  /**
   * Returns the value of the '<em><b>Deferstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Deferstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deferstmt</em>' containment reference.
   * @see #setDeferstmt(deferstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstatement_Deferstmt()
   * @model containment="true"
   * @generated
   */
  deferstmt getDeferstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.statement#getDeferstmt <em>Deferstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deferstmt</em>' containment reference.
   * @see #getDeferstmt()
   * @generated
   */
  void setDeferstmt(deferstmt value);

} // statement
