/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>switchstmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.switchstmt#getExprswitchstmt <em>Exprswitchstmt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.switchstmt#getTypeswitchstmt <em>Typeswitchstmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getswitchstmt()
 * @model
 * @generated
 */
public interface switchstmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Exprswitchstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exprswitchstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprswitchstmt</em>' containment reference.
   * @see #setExprswitchstmt(exprswitchstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getswitchstmt_Exprswitchstmt()
   * @model containment="true"
   * @generated
   */
  exprswitchstmt getExprswitchstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.switchstmt#getExprswitchstmt <em>Exprswitchstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exprswitchstmt</em>' containment reference.
   * @see #getExprswitchstmt()
   * @generated
   */
  void setExprswitchstmt(exprswitchstmt value);

  /**
   * Returns the value of the '<em><b>Typeswitchstmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typeswitchstmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typeswitchstmt</em>' containment reference.
   * @see #setTypeswitchstmt(typeswitchstmt)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getswitchstmt_Typeswitchstmt()
   * @model containment="true"
   * @generated
   */
  typeswitchstmt getTypeswitchstmt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.switchstmt#getTypeswitchstmt <em>Typeswitchstmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typeswitchstmt</em>' containment reference.
   * @see #getTypeswitchstmt()
   * @generated
   */
  void setTypeswitchstmt(typeswitchstmt value);

} // switchstmt
