/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>typeswitchstmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.typeswitchstmt#getTypeswitchguard <em>Typeswitchguard</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.typeswitchstmt#getTypecaseclause <em>Typecaseclause</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#gettypeswitchstmt()
 * @model
 * @generated
 */
public interface typeswitchstmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Typeswitchguard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typeswitchguard</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typeswitchguard</em>' containment reference.
   * @see #setTypeswitchguard(typeswitchguard)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#gettypeswitchstmt_Typeswitchguard()
   * @model containment="true"
   * @generated
   */
  typeswitchguard getTypeswitchguard();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.typeswitchstmt#getTypeswitchguard <em>Typeswitchguard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Typeswitchguard</em>' containment reference.
   * @see #getTypeswitchguard()
   * @generated
   */
  void setTypeswitchguard(typeswitchguard value);

  /**
   * Returns the value of the '<em><b>Typecaseclause</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.typecaseclause}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Typecaseclause</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Typecaseclause</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#gettypeswitchstmt_Typecaseclause()
   * @model containment="true"
   * @generated
   */
  EList<typecaseclause> getTypecaseclause();

} // typeswitchstmt
