/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unaryexpr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unaryexpr#getExpressionaux <em>Expressionaux</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unaryexpr#getPrimaryexpr <em>Primaryexpr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unaryexpr#getUNARY_OP <em>UNARY OP</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.unaryexpr#getUnaryexpr <em>Unaryexpr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunaryexpr()
 * @model
 * @generated
 */
public interface unaryexpr extends expression
{
  /**
   * Returns the value of the '<em><b>Expressionaux</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expressionaux</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expressionaux</em>' containment reference.
   * @see #setExpressionaux(expressionaux)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunaryexpr_Expressionaux()
   * @model containment="true"
   * @generated
   */
  expressionaux getExpressionaux();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unaryexpr#getExpressionaux <em>Expressionaux</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expressionaux</em>' containment reference.
   * @see #getExpressionaux()
   * @generated
   */
  void setExpressionaux(expressionaux value);

  /**
   * Returns the value of the '<em><b>Primaryexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primaryexpr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primaryexpr</em>' containment reference.
   * @see #setPrimaryexpr(primaryexpr)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunaryexpr_Primaryexpr()
   * @model containment="true"
   * @generated
   */
  primaryexpr getPrimaryexpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unaryexpr#getPrimaryexpr <em>Primaryexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primaryexpr</em>' containment reference.
   * @see #getPrimaryexpr()
   * @generated
   */
  void setPrimaryexpr(primaryexpr value);

  /**
   * Returns the value of the '<em><b>UNARY OP</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>UNARY OP</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>UNARY OP</em>' attribute.
   * @see #setUNARY_OP(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunaryexpr_UNARY_OP()
   * @model
   * @generated
   */
  String getUNARY_OP();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unaryexpr#getUNARY_OP <em>UNARY OP</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>UNARY OP</em>' attribute.
   * @see #getUNARY_OP()
   * @generated
   */
  void setUNARY_OP(String value);

  /**
   * Returns the value of the '<em><b>Unaryexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unaryexpr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unaryexpr</em>' containment reference.
   * @see #setUnaryexpr(unaryexpr)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getunaryexpr_Unaryexpr()
   * @model containment="true"
   * @generated
   */
  unaryexpr getUnaryexpr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.unaryexpr#getUnaryexpr <em>Unaryexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unaryexpr</em>' containment reference.
   * @see #getUnaryexpr()
   * @generated
   */
  void setUnaryexpr(unaryexpr value);

} // unaryexpr
